spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: springstudent
    password: springstudent
  application:
    name: ems

  jpa:
    hibernate:
#      validate
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  security:
    user:
      name: disabled
      password: disabled

server:
  port: 8080

jwt:
  secret: 7ejXS1AkDO1MpH62/ytdrSSQdYj/Eq0GYjok6WNlDTM=
  expiration: 86400000   # 1 day in milliseconds

logging:
  level:
    org.springframework.security: INFO





